<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GDA Panel 6</name>
   <tag></tag>
   <elementGuidId>68baa6d7-9f49-4e55-a526-49ad9461003c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-c1e133be-caa8-43a1-b9ee-6552f14645fc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-c1e133be-caa8-43a1-b9ee-6552f14645fc</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'panel-c1e133be-caa8-43a1-b9ee-6552f14645fc' and (text() = 'BUYER FAQsHave questions about purchasing items, how your account works or how to get in contact with sellers? Visit our Buyer FAQ page to learn more about being a Buyer on GDA.LEARN MORE' or . = 'BUYER FAQsHave questions about purchasing items, how your account works or how to get in contact with sellers? Visit our Buyer FAQ page to learn more about being a Buyer on GDA.LEARN MORE')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-c1e133be-caa8-43a1-b9ee-6552f14645fc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section section-banner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BUYER FAQsHave questions about purchasing items, how your account works or how to get in contact with sellers? Visit our Buyer FAQ page to learn more about being a Buyer on GDA.LEARN MORE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-c1e133be-caa8-43a1-b9ee-6552f14645fc&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-c1e133be-caa8-43a1-b9ee-6552f14645fc']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react_0HM3469BHU5MU']/div/div/div[15]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MULTIPLE PROCUREMENT OPTIONS'])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div</value>
   </webElementXpaths>
</WebElementEntity>
