<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GDA Panel 7</name>
   <tag></tag>
   <elementGuidId>483dd0d5-d165-4b81-b904-7093680e47e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-58d2a9b2-a861-4b3e-8ecc-54e6b9d3ef6a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-58d2a9b2-a861-4b3e-8ecc-54e6b9d3ef6a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'panel-58d2a9b2-a861-4b3e-8ecc-54e6b9d3ef6a' and (text() = 'SELLER FAQsWant to set upload more items, add different delivery methods, or check on your orders? Visit our Seller FAQ page to learn more about being a seller on GDA and how to use your account. LEARN MORE' or . = 'SELLER FAQsWant to set upload more items, add different delivery methods, or check on your orders? Visit our Seller FAQ page to learn more about being a seller on GDA and how to use your account. LEARN MORE')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-58d2a9b2-a861-4b3e-8ecc-54e6b9d3ef6a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section section-banner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELLER FAQsWant to set upload more items, add different delivery methods, or check on your orders? Visit our Seller FAQ page to learn more about being a seller on GDA and how to use your account. LEARN MORE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-58d2a9b2-a861-4b3e-8ecc-54e6b9d3ef6a&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-58d2a9b2-a861-4b3e-8ecc-54e6b9d3ef6a']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react_0HM3469BHU5MU']/div/div/div[16]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LEARN MORE'])[3]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUYER FAQs'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div</value>
   </webElementXpaths>
</WebElementEntity>
