<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GDA Panel5</name>
   <tag></tag>
   <elementGuidId>69dd22fd-862c-4aab-9946-07a828db9787</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#panel-213cee4b-a2a6-43c0-9f26-83f64d2009cb_52979</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-213cee4b-a2a6-43c0-9f26-83f64d2009cb_52979']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-213cee4b-a2a6-43c0-9f26-83f64d2009cb_52979</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VETTED BUYERS &amp; SELLERS All users on the GDA marketplace go through a vetting process to ensure a trusted environment.EVALUATED ITEMS All items go through an evaluation process before they are made available on the GDA marketplace.MULTIPLE PROCUREMENT OPTIONS Users can procure directly through GDA through other agencies using different funding.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-213cee4b-a2a6-43c0-9f26-83f64d2009cb_52979&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-213cee4b-a2a6-43c0-9f26-83f64d2009cb_52979']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react_0HM34PHLCDSUI']/div/div/div[14]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WHY USE THE GDA MARKETPLACE'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER VETTING AND ITEM EVALUATION PROCESS'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div</value>
   </webElementXpaths>
</WebElementEntity>
