<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_COVID-19 Panel 3</name>
   <tag></tag>
   <elementGuidId>d7d9f648-f55c-439f-8581-35c196a24c25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-3876a79c-b225-46e1-af7e-0443e70e7372']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-3876a79c-b225-46e1-af7e-0443e70e7372</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'panel-3876a79c-b225-46e1-af7e-0443e70e7372' and (text() = 'COVID-19 eCATALOGUE INFORMATIONAll diagnostic tests listed on COVID-19 eCatalogue are from public global databases and is being continually updated as more tests are developed and become commercially available. To learn more about the tests that are listed on the catalogue, you can click below.TYPE OF TESTS AVAILABLE' or . = 'COVID-19 eCATALOGUE INFORMATIONAll diagnostic tests listed on COVID-19 eCatalogue are from public global databases and is being continually updated as more tests are developed and become commercially available. To learn more about the tests that are listed on the catalogue, you can click below.TYPE OF TESTS AVAILABLE')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-3876a79c-b225-46e1-af7e-0443e70e7372</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section section-banner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COVID-19 eCATALOGUE INFORMATIONAll diagnostic tests listed on COVID-19 eCatalogue are from public global databases and is being continually updated as more tests are developed and become commercially available. To learn more about the tests that are listed on the catalogue, you can click below.TYPE OF TESTS AVAILABLE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-3876a79c-b225-46e1-af7e-0443e70e7372&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-3876a79c-b225-46e1-af7e-0443e70e7372']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react_0HM3381N2O8PS']/div/div/div[6]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROCURE'])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FILTER'])[1]/following::div[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
   </webElementXpaths>
</WebElementEntity>
